import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Toaster } from "react-hot-toast";
import Layout from "./(root)/layout";
import Providers from "@/lib/Providers";
import CacheProviders from "@/lib/CacheProviders";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <CacheProviders>
            <Toaster />
            {children}
          </CacheProviders>
        </Providers>
      </body>
    </html>
  );
}
